apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: eh1jzfawk-java-springboot 
  janus-idp.io/tekton: eh1jzfawk-java-springboot
  backstage.io/kubernetes-id: eh1jzfawk-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: eh1jzfawk-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml